-- ============================================================
-- BAGDROP — Indemnity Bond digitization
-- Run in Supabase Dashboard → SQL Editor
--
-- New workflow steps inserted into the Booking Workflow:
--   confirmed → indemnity_bond_sent → indemnity_bond_signed → invoice_generated → ...
-- (bookings.status is already TEXT, not an enum — see
--  BOOKING_STATUS_ENUM_FIX.sql — so no ALTER needed there, these two
--  new values are simply new strings the frontend/backend now recognize.)
--
-- One row per booking (booking_id is UNIQUE) — a resubmission request
-- resets the same row rather than creating a new one, so there's always
-- exactly one current bond per booking.
-- ============================================================

CREATE TABLE IF NOT EXISTS indemnity_bonds (
  id                     UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  booking_id             UUID        NOT NULL UNIQUE REFERENCES bookings(id) ON DELETE CASCADE,

  -- Secure link (Step 2) — https://www.bagdrop.co/indemnity/{secure_token}
  secure_token           TEXT        UNIQUE NOT NULL,
  token_expires_at       TIMESTAMPTZ NOT NULL,

  -- Step 1 — send tracking
  sent_at                TIMESTAMPTZ,
  sent_via               TEXT[]      DEFAULT '{}',   -- e.g. {'email'} or {'email','whatsapp'}

  -- Step 3 — OTP identity verification (the OTP itself is generated/checked
  -- via the existing auth_otps table + /api/auth/send-otp /verify-otp
  -- infrastructure; this just records the outcome for this bond)
  otp_contact            TEXT,                        -- email or phone that was verified
  otp_verified           BOOLEAN     DEFAULT false,
  otp_verified_at        TIMESTAMPTZ,

  -- Step 4 — customer-provided identity fields captured at signing time
  aadhaar_number         TEXT,
  passport_number        TEXT,
  licence_number         TEXT,
  bond_date              DATE,
  bond_place             TEXT,

  -- Step 5 — signature
  signed_at              TIMESTAMPTZ,

  -- Step 6/7 — final outputs, stored in the private 'indemnity-documents'
  -- Supabase Storage bucket (paths only — served via short-lived signed
  -- URLs generated on demand, never public, since these are Aadhaar/
  -- passport-grade PII documents)
  signed_pdf_path         TEXT,
  aadhaar_doc_path        TEXT,
  passport_doc_path       TEXT,
  flight_ticket_doc_path  TEXT,
  extra_doc_path          TEXT,

  -- Step 8 — admin review
  document_status        TEXT        DEFAULT 'pending',
    -- pending | approved | rejected | resubmission_requested
  reviewed_by             TEXT,
  reviewed_at             TIMESTAMPTZ,
  review_note             TEXT,

  submitted_at            TIMESTAMPTZ,

  status_history          JSONB       DEFAULT '[]',
  created_at              TIMESTAMPTZ DEFAULT NOW(),
  updated_at              TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_indemnity_bonds_booking_id     ON indemnity_bonds(booking_id);
CREATE INDEX IF NOT EXISTS idx_indemnity_bonds_secure_token   ON indemnity_bonds(secure_token);
CREATE INDEX IF NOT EXISTS idx_indemnity_bonds_document_status ON indemnity_bonds(document_status);

-- ── updated_at trigger (idempotent — same function used by trip_sheets) ──
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_indemnity_bonds_updated_at ON indemnity_bonds;
CREATE TRIGGER set_indemnity_bonds_updated_at
  BEFORE UPDATE ON indemnity_bonds
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ── RLS — service_role only, mirrors every other table in this project ──
ALTER TABLE indemnity_bonds ENABLE ROW LEVEL SECURITY;

CREATE POLICY "service_role_all_indemnity_bonds"
  ON indemnity_bonds FOR ALL TO service_role USING (true) WITH CHECK (true);

-- ============================================================
-- Storage — indemnity-documents bucket (PRIVATE)
--
-- Unlike the public 'quotes' bucket, this bucket stays PRIVATE: it holds
-- Aadhaar/passport-grade PII. Nothing is ever served via a public URL —
-- the admin dashboard and the (OTP-gated) public signing page both read
-- files through server-side signed URLs generated by supabaseAdmin, which
-- uses the service_role key and bypasses RLS entirely. The policies below
-- are a safety belt only, matching the pattern used for the quotes bucket.
-- ============================================================

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'indemnity-documents',
  'indemnity-documents',
  false,                                     -- PRIVATE — no public URL access
  10485760,                                  -- 10 MB per file
  ARRAY['application/pdf', 'image/jpeg', 'image/png']
)
ON CONFLICT (id) DO UPDATE SET
  public             = EXCLUDED.public,
  file_size_limit    = EXCLUDED.file_size_limit,
  allowed_mime_types = EXCLUDED.allowed_mime_types;

CREATE POLICY "indemnity_documents_service_role_all"
ON storage.objects FOR ALL
USING ( bucket_id = 'indemnity-documents' AND auth.role() = 'service_role' )
WITH CHECK ( bucket_id = 'indemnity-documents' AND auth.role() = 'service_role' );

-- ============================================================
-- Configurable token expiry — stored in the existing `settings`
-- key/value table (already used for payment_upi etc.), so it can be
-- changed from Admin Settings later without a code deploy.
-- Falls back to 7 days in code if this row is missing.
-- ============================================================
INSERT INTO settings (key, value)
VALUES ('indemnity_link_expiry_days', '7')
ON CONFLICT (key) DO NOTHING;
